package org.jinghouyu.office.word.object.lcb;

import java.io.IOException;
import java.io.InputStream;

import org.jinghouyu.office.basic.compound.utils.IOUtils;
import org.jinghouyu.office.basic.compound.utils.littleendian.LeInteger;

public class Lcb2003 extends Lcb2002 {

	private long fcHplxsdr;
	private long lcbHplxsdr;
	private long fcSttbfBkmkSdt;
	private long lcbSttbfBkmkSdt;
	private long fcPlcfBkfSdt;
	private long lcbPlcfBkfSdt;
	private long fcPlcfBklSdt;
	private long lcbPlcfBklSdt;
	private long fcCustomXForm;
	private long lcbCustomXForm;
	private long fcSttbfBkmkProt;
	private long lcbSttbfBkmkProt;
	private long fcPlcfBkfProt;
	private long lcbPlcfBkfProt;
	private long fcPlcfBklProt;
	private long lcbPlcfBklProt;
	private long fcSttbProtUser;
	private long lcbSttbProtUser;
	private long fcUnused;
	private long lcbUnused;
	private long fcPlcfpmiOld;
	private long lcbPlcfpmiOld;
	private long fcPlcfpmiOldInline;
	private long lcbPlcfpmiOldInline;
	private long fcPlcfpmiNew;
	private long lcbPlcfpmiNew;
	private long fcPlcfpmiNewInline;
	private long lcbPlcfpmiNewInline;
	private long fcPlcflvcOld;
	private long lcbPlcflvcOld;
	private long fcPlcflvcOldInline;
	private long lcbPlcflvcOldInline;
	private long fcPlcflvcNew;
	private long lcbPlcflvcNew;
	private long fcPlcflvcNewInline;
	private long lcbPlcflvcNewInline;
	private long fcPgdMother;
	private long lcbPgdMother;
	private long fcBkdMother;
	private long lcbBkdMother;
	private long fcAfdMother;
	private long lcbAfdMother;
	private long fcPgdFtn;
	private long lcbPgdFtn;
	private long fcBkdFtn;
	private long lcbBkdFtn;
	private long fcAfdFtn;
	private long lcbAfdFtn;
	private long fcPgdEdn;
	private long lcbPgdEdn;
	private long fcBkdEdn;
	private long lcbBkdEdn;
	private long fcAfdEdn;
	private long lcbAfdEdn;
	private long fcAfd;
	private long lcbAfd;

	
	public void parse(InputStream in) throws IOException {
		super.parse(in);
		this.fcHplxsdr = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbHplxsdr = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcSttbfBkmkSdt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbSttbfBkmkSdt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfBkfSdt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfBkfSdt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfBklSdt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfBklSdt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcCustomXForm = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbCustomXForm = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcSttbfBkmkProt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbSttbfBkmkProt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfBkfProt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfBkfProt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfBklProt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfBklProt = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcSttbProtUser = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbSttbProtUser = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcUnused = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbUnused = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfpmiOld = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfpmiOld = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfpmiOldInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfpmiOldInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfpmiNew = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfpmiNew = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcfpmiNewInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcfpmiNewInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcflvcOld = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcflvcOld = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcflvcOldInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcflvcOldInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcflvcNew = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcflvcNew = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPlcflvcNewInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPlcflvcNewInline = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPgdMother = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPgdMother = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcBkdMother = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbBkdMother = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcAfdMother = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbAfdMother = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPgdFtn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPgdFtn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcBkdFtn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbBkdFtn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcAfdFtn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbAfdFtn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcPgdEdn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbPgdEdn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcBkdEdn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbBkdEdn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcAfdEdn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbAfdEdn = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.fcAfd = LeInteger.toInteger(IOUtils.readFully(in, 4));
		this.lcbAfd = LeInteger.toInteger(IOUtils.readFully(in, 4));
	}
}
